articles/urls.py
from django.conf.urls import url
from . import views
from .views import TagIndexView,ArticleIndex

app_name = 'articles'

urlpatterns = [
    url(r'(?P<id>\d+)/article_edit/$', views.article_edit, name="article_edit"),
    url(r'(?P<id>\d+)/article_delete/$', views.article_delete, name="article_delete"),
    url(r'^$', ArticleIndex.as_view(), name="list"),
    url(r'^$', views.article_list, name="List"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^tag/(?P<slug>[-\w]+)/$', TagIndexView.as_view(), name='tagged'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

contact/urls.py
from django.conf.urls import url
from . import  views



urlpatterns = [
    url(r'^/$',views.contact, name="contact"),
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from contact.views import contact


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'contact/$',contact,name="contact"),
    url(r'^about/$', views.about,name="about"),
    url(r'^$', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils import timezone

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT, default=None)

    tags = TaggableManager()


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    #approved_comment = models.BooleanField(default=False)

    #def approve(self):
         #self.approved_comment = True
          #self.save()

    def __str__(self):
        return '{}.{}'.format(self.post.title, str(self.author))

articles/forms.py
from django import forms
from . import models
from .models import Article, Comment
from django.contrib.auth.models import User

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb','tags']


class ArticleEditForm(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb','tags']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

articles/views.py
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from taggit.models import Tag
from django.views.generic import DetailView, ListView
from .forms import  *
from . import forms
from .forms import CreateArticle, CommentForm


from .models import Article
from django.contrib.auth.decorators import login_required







class TagMixin(object):
    def get_context_data(self,**kwargs):
        context = super(TagMixin,self).get_context_data(**kwargs)
        context['tags']= Tag.objects.all()
        return context

class ArticleIndex(TagMixin,ListView):
    template_name = 'articles/article_list.html'
    model = Article
    paginate_by = '1000'
    queryset = Article.objects.all()
    context_object_name = 'articles'

    ordering = ['-date']




def article_list(request):
    articles = Article.objects.all().order_by('-date');
    query = request.GET.get("q")
    if query:
        articles = articles.filter(title__icontains=query)
    return render(request, 'articles/article_list.html', { 'articles': articles })


def article_detail(request, slug):  # return HttpResponse(slug)
    post = get_object_or_404(Article, slug=slug)
    comments = Comment.objects.filter(post=post).order_by('.date')
    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            text = request.POST.get('text')
            comment = Comment.objects.create(post=post, author=request.user.username, text=text)
            comment.save()
            return HttpResponseRedirect(request.path_info)
    else:
        comment_form = CommentForm()
        context={
            'article': post,
            'comments': comments,
            'comment_form': comment_form,
        }

        return  render(request, 'articles/article_detail.html', context)




class TagIndexView(TagMixin,ListView):
    template_name = 'articles/article_list.html'
    model = Article
    paginate_by = '10'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.filter(tags__slug=self.kwargs.get('slug'))


def article_edit(request,id):
    post= get_object_or_404(Article,id=id)
    if post.author !=request.user:
        raise Http404()
    if request.method=="POST":
        form = ArticleEditForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()
            return redirect('articles:list')
    else:
        form = ArticleEditForm(instance=post)
        context={
            'form':form,
            'post':post,
        }
        return  render(request,'articles/article_edit.html',context)

def article_delete(request, id):
    post = get_object_or_404(Article, id=id)
    if post.author != request.user:
        raise Http404()
    post.delete()
    return redirect('/')


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            form.save_m2m()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}


<hr>
<div class="main-comment-section">
    {{ comments.count}} Comment{{ comments|pluralize }}
    {% for comment in comments %}
    <blockquote class="blockquote">
      <p class="mb-0">{{ comment.content }}</p>
      <footer class="blockquote-footer">by <cite title="Source Title">{{ comment.user|capfirst}}</cite></footer>
</blockquote>
    {% endfor %}
</div>

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <h3>Written by {{ article.author.username }}</h3>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
        <p>{{article.tags.all|join:", "}}</p>
    </div>
</div>

<hr>
    {% if article.author == request.user %}
<div class="section-1" style="float: right;">
<a href="{% url 'articles:article_edit' id=article.id %}">
    <button type="button" class="btn btn-outline-success">Edit</button>
</a>
</div>
    {% endif %}


<form method="post">
  {% csrf_token %}
  {{ comment_form.as_p }}
  <input type="submit" value="Submit" class="btn btn-outline.success">

</form>

{% for comment in article.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
{% endblock %}

articles/templates/articles/article_edit.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="article_edit">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-success">

    </form>
    </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <div class="search">
    <form method="GET" action="" class="search" >
  <input type="text" name='q' placeholder="search"class="button1"/>
  <input type="submit" value="Search"class="button2"/>
    </form>
        </div>

    <h1>Articles List</h1>
    <div class="panel-heading">
    <h2><i>Tags</i></h2>

    <div class="panel-body">
    <ul class="tags">
        {% for tag in tags %}
        <li><a href="{% url 'articles:tagged' tag.slug %}">{{ tag.name }}</a> </li>
        {% empty %}
            <li><a href="/articles/">Click here to show tags</a></li>
        <li>No Tags Right now</li>
        {% endfor %}
    </ul>
    </div>
    </div>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
             <h2><a href="{% url 'articles:detail' slug=article.slug %}"><h2><b><i><u>{{ article.title }}</u></i></b></h2>

            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
                <ul>
                  {% for tag in article.tags.all %}
                    <li> {{ tag.name }} </li>
                  {% endfor %}
                </ul>
            <img src="{{ article.thumb.url }}" alt="" height="150" width="150">
             </a>


                <p class="author">added by {{ article.author.username }}</p>
            </a>
        </div>
    {% endfor %}

    </div>
{% endblock %}