accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

articles/urls.py
from django.conf.urls import url
from . import views
from .views import TagIndexView,ArticleIndex

app_name = 'articles'

urlpatterns = [
    url(r'(?P<id>\d+)/article_edit/$', views.article_edit, name="article_edit"),
    url(r'(?P<id>\d+)/article_delete/$', views.article_delete, name="article_delete"),
    url(r'^$', ArticleIndex.as_view(), name="list"),
    url(r'^$', views.article_list, name="List"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^tag/(?P<slug>[-\w]+)/$', TagIndexView.as_view(), name='tagged'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

contact/urls.py
from django.conf.urls import url
from . import  views



urlpatterns = [
    url(r'^/$',views.contact, name="contact"),
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from contact.views import contact


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'contact/$',contact,name="contact"),
    url(r'^about/$', views.about,name="about"),
    url(r'^$', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

class Contact(models.Model):
    first_name= models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()

    def _str_(self):
        return f'{self.first_name}{self.last_name}'

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model= Contact
        fields =('first_name','last_name','email','message')

contact/views.py
from django.shortcuts import render
from .forms import ContactForm

def contact(request):
    template ="contact.html"
    if request.method=="POST":
            form=ContactForm(request.POST)

            if form.is_valid():
                form.save()
    else:
            form= ContactForm()
    context = {
        'form':form
    }
    return render(request,template,context)

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About us</h1>
    <p1>We are Django blog developers</p1>
</body>
</html>

templates/base_layout.html
{% load static from static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Tech-Science</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="container">
        <div id="'branding">
            <h1><a href="{% url 'articles:list' %}"><span class="highlight">Tech-Science</span> BLOG</a></h1>
        </div>
            <nav >
                <ul>

                    <li><a href="/admin/">Admin Panel</a></li>
                    <li><a href="/contact/">Contact Us</a></li>
                                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    <footer>
      <p>Tech-Science BLOG, Copyright &copy; 2019</p>
    </footer>
    </body>
</html>

templates/contact.html
{% extends 'base_layout.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">SEND</button>

</form>

{% endblock %}

templates/homepage.html
<!--
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HomePage</title>
</head>
<body>
     <h1>This is Homepage</h1>
     <p>Welcome to Django</p>
</body>
</html>-->
<script>
  window.location.replace("./articles/")
</script>